version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: kirill
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-net

  vault:
    image: vault:1.12.7
    container_name: vault-server
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: http://vault-server:8200 #http://127.0.0.1:8200 # VAULT_ADDR: http://vault-server:8200
    ports:
      - "8200:8200"

    volumes:
      - /home/oneb1za/vault/policies:/vault/policies
      - vault-data:/vault/data
    networks:
      - app-net
    user: "${UID}:${GID}" # чтобы овнер был текущий пользователь а не root

  auth-dj-service:
    image: auth_service_app:latest
    container_name: auth-service
    ports:
      - "8000:8000"
    environment:
      - VAULT_ADDR=http://vault-server:8200
      - VAULT_TOKEN=root  # Используйте безопасный токен для продакшена
    networks:
      - app-net


networks:
  app-net:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  vault-data:

