# Generated by Django 4.2.5 on 2024-08-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_staff_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], default='', max_length=1, verbose_name='Гендер'),
        ),
    ]
