# Generated by Django 4.2.5 on 2024-09-06 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofilesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofilesettings',
            options={'verbose_name': 'Настройки профиля', 'verbose_name_plural': 'Настройки профиля'},
        ),
        migrations.AlterField(
            model_name='userprofilesettings',
            name='invisible_friendlist',
            field=models.BooleanField(blank=True, default=False, help_text='Виден ли список ваших друзей', null=True),
        ),
        migrations.AlterField(
            model_name='userprofilesettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
